### ISSUE TITLE
This localhost page can’t be foundNo webpage was found for the web address: http://localhost:5173/ HTTP ERROR 404

### ISSUE THREAD

**Issue by rahulguggilam** [HydraPhyzer/Decentralized-Google-Drive#1]
I have compiled and deployed the given smart contract where should I paste it and how to run the application there is no clarity about running the application in the repository. and  I have kept my API key ,secret in .env file in the main directory

**Comment by HydraPhyzer** [comment]
Hey @Rahulguggilam2003 Are You Still Facing Issues ? If You Have Any Queries, Let Me Know.

**Comment by Rahulguggilam2003** [comment]
hello @HydraPhyzer I am facing this issue Can you help me to remove the error while uploading file to Pinata I have created an API key and I have included it in FileUpload.jsx 
FileUpload.jsx:13     POST https://api.pinata.cloud/pinning/pinFileToIPFS 403 (Forbidden)
