### ISSUE TITLE
FileUpload.jsx:13     POST https://api.pinata.cloud/pinning/pinFileToIPFS 403 (Forbidden)

### ISSUE THREAD

**Issue by rahulguggilam** [HydraPhyzer/Decentralized-Google-Drive#2]
when i was trying to upload a file using pinata API this error has been encountered, I have included pinata API key and secret in FileUpload.jsx

**Comment by HydraPhyzer** [comment]
Hey @Rahulguggilam2003. This is Actually an Error from Your Pinata Account Side. This is Not An Error From Our Website Side. Please Double Check Your Api or Secret Key and Makes Sure its Corrects and also Check the Access Control Settings on You Pinata Account.

Report Me ASAP If Error Still Persists. I Will Be Here To Help Anytime. 

Lastly There is an Advice, Please Debug By Console.log Whether Your Secrets Are Properly Being Imported or Not If You Have Secrets or Key in You .env File

**Comment by Rahulguggilam2003** [comment]
hello @HydraPhyzer I have been trying on it but the error was not solved and I doesn't make any changes in the code
<img width="552" alt="proof" src="https://github.com/HydraPhyzer/Decentralized-Google-Drive/assets/94698414/0ec12f4d-e60a-490e-823e-430cd498f224">

**Comment by rahulguggilam** [comment]
hello @HydraPhyzer I have been trying on it but the error was not solved and I didn't make any changes in the code
<img width="468" alt="error" src="https://github.com/HydraPhyzer/Decentralized-Google-Drive/assets/94698414/644f0cba-b837-444a-bc41-bc0097c63251">

**Comment by HydraPhyzer** [comment]
Hey @Rahulguggilam2003 Please Make Sure That You Followed The Same Steps I Mentioned in README.md File, You Have to Run Hardhat Local Network With `npx hardhat node` Command
